name: common
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test: ^1.21.0
  mocktail: ^0.3.0
  flutterando_analysis: ^0.0.2
dependencies:
  dart_result: ^1.0.0
  uno: ^1.1.0
